import { expect, test } from "bun:test"
import { readFile } from "node:fs/promises"
import { fileURLToPath } from "node:url"
import { parseGLB } from "../../lib/gltf/parseGLB"
import { renderGLTFToPNGFromGLB } from "../../lib/render/renderGLTFToPNGFromGLB"
import "../fixtures/preload"

test("showHiddenEdges outlines only the enclosure in a core 3D model", async () => {
  // Generated by tscircuit/core's enclosure-fdm-box-usb-cutout test. The
  // enclosure node is tagged with extras.poppygl.showHiddenEdges; the PCB and
  // USB-C connector nodes intentionally remain untagged.
  const glbPath = fileURLToPath(
    new URL(
      "../fixtures/assets/enclosure-fdm-box-usb-cutout.glb",
      import.meta.url,
    ),
  )
  const glb = await readFile(glbPath)
  const glbArrayBuffer = Uint8Array.from(glb).buffer
  const { gltf } = parseGLB(glbArrayBuffer)
  expect(
    gltf.nodes.map((node: any) => ({
      name: node.name,
      showHiddenEdges: node.extras?.poppygl?.showHiddenEdges ?? false,
    })),
  ).toEqual([
    { name: "Box0", showHiddenEdges: false },
    { name: "USB1", showHiddenEdges: false },
    { name: "unnamed_enclosurefdmbox1", showHiddenEdges: true },
  ])

  const png = await renderGLTFToPNGFromGLB(glb, {
    width: 1024,
    height: 1024,
    camPos: [30, 24, 50],
    lookAt: [0, 0, 3.5],
    backgroundColor: [1, 1, 1],
    grid: false,
  })

  await expect(png).toMatchPngSnapshot(import.meta.path)
})
